name: Spring Boot Deploy
run-name: CI (${{ inputs.environment || 'development' }}) by @${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        default: development
        options:
          - development
          - homolog
          - production

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # push/PR usam "development"; execução manual escolhe o ambiente
    environment: ${{ inputs.environment || 'development' }}

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Build Docker image
        run: docker build -t minha-api .

      - name: Run Docker container
        env:
          # sensíveis (secrets)
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          # não sensíveis (vars)
          JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION }}
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{ vars.MYSQL_DATABASE }}?allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATA_REDIS_HOST: localhost
          SPRING_DATA_REDIS_PORT: 6379
        run: |
          docker run -d --name minha-api --network host \
            -e JWT_SECRET \
            -e JWT_EXPIRATION \
            -e SPRING_DATASOURCE_URL \
            -e SPRING_DATASOURCE_USERNAME \
            -e SPRING_DATASOURCE_PASSWORD \
            -e SPRING_DATA_REDIS_HOST \
            -e SPRING_DATA_REDIS_PORT \
            minha-api

      - name: Show logs on failure
        if: failure()
        run: docker logs minha-api